version: '3.8'

services:
  roman-numeral-service-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: roman-numeral-service-dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ENV=DEV
    volumes:
      - .:/app
      - /app/node_modules
      - ./env:/app/env:ro
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - roman-numeral-dev-network

  # Development DataDog Agent
  datadog-agent-dev:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent-dev
    environment:
      - DD_API_KEY=${DD_API_KEY:-}
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8126:8126"  # APM
      - "8125:8125/udp"  # StatsD
    restart: unless-stopped
    profiles:
      - monitoring
    networks:
      - roman-numeral-dev-network

networks:
  roman-numeral-dev-network:
    driver: bridge 